#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd in the specified format.

while IFS=: read -r username _ userid _ _ _ homedir _ shell; do
    echo "The user $username is part of the $(id -g $username) gang, lives in $homedir and rides $shell."
    echo "USER ID's place is protected by the passcode $(grep $username /etc/shadow | cut -d: -f2), more info about the user here: $(grep $username /etc/passwd | cut -d: -f7)"
done < /etc/passwd
