#!/usr/bin/env bash
# This script prints the time for 12 hours and 59 minutes.

i=0
while [ $i -le 12 ]; do
    j=1
    while [ $j -le 59 ]; do
        echo "$i hours $j minutes"
        ((j++))
    done
    ((i++))
done
