#!/usr/bin/env bash
# This script manages its PID and responds to signals.

# Trap signals and define signal handlers
trap 'echo "I hate the kill command" && exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid && exit' SIGQUIT SIGTERM

# Create PID file
echo "$$" > /var/run/myscript.pid

# Display message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done

